global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webflux-user-api'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s